core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /
admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

api_bundle:
    type: rest
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /
    defaults: {_format: json}
    
