realtime_database:
    resource: "@RealtimeDatabaseBundle/Controller/"
    type:     annotation
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /
    
admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /
    
