security:
    encoders:
        CoreBundle\Entity\BaseActor:
            algorithm: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_COMPANY, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_COMPANY, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: CoreBundle:BaseActor }

    firewalls:
        #oauth server
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: main
                check_path: login_check
                login_path: login
            anonymous: true
            context: test_connect
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true # Needed to allow access to oauth pages
    access_control:
        - { path: ^/admin/actor, roles: [ROLE_ADMIN] }
        - { path: ^/admin/subscription, roles: [ROLE_ADMIN] }
        - { path: ^/admin/newsletter, roles: [ROLE_ADMIN] }
        - { path: ^/admin/shipping, roles: [ROLE_ADMIN] }
        - { path: ^/admin/sliders, roles: [ROLE_ADMIN] }
        - { path: ^/admin/dashboard, roles: [ROLE_ADMIN, ROLE_COMPANY] }
        - { path: ^/admin/analitycs, roles: [ROLE_ADMIN] }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_COMPANY, ROLE_USER] }
        - { path: ^/company/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/company, roles: [ROLE_COMPANY] }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/oauth/v2/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
