# FOSAuthServerBundle
#fos_oauth_server_token:
#    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
#
#fos_oauth_server_authorize:
#    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    
app_api:
    resource: "@ApiBundle/Controller/Api"
    type:     annotation
    prefix:   /api