security:
    encoders:
        CoreBundle\Entity\BaseActor:
            algorithm: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_COMPANY, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_COMPANY, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: CoreBundle:BaseActor }

    firewalls:
        admin:
            http_basic: ~
            anonymous: ~
            pattern:    ^/admin/.*
            form_login:
                provider: main
                login_path:  /admin/login
                check_path:  /admin/login_check
                use_referer: true
                success_handler: authentication_handler
                failure_handler: authentication_handler
                default_target_path: /admin
            logout:
                path: admin_logout   
                target: /admin/login
            switch_user:
                role: ROLE_ADMIN
            context: website
        company:
            http_basic: ~
            anonymous: ~
            pattern:    ^/company/.*
            form_login:
                provider: main
                login_path:  /company/login
                check_path:  /company/login_check
                use_referer: true
                success_handler: authentication_handler
                failure_handler: authentication_handler
                default_target_path: /company
            logout:
                path: company_logout
                target: /company/login
            switch_user:
                role: ROLE_ADMIN
                provider: main
            context: website
        #oauth server
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: main
                check_path: /oauth/v2/auth/login_check
                login_path: /oauth/v2/auth/login
            anonymous: true
            context: test_connect
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true # Needed to allow access to oauth pages
        user:
            http_basic: ~
            anonymous: ~
            context: test_connect
            pattern:    ^/
            form_login:
                login_path:  /login
                check_path:  /login_check
                use_referer: true
                success_handler: authentication_handler
                failure_handler: authentication_handler
            logout:
                path:   /logout
                target: /
#                success_handler: authentication_handler
            anonymous: true
            remember_me:
                secret:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
    access_control:
        - { path: ^/admin/actor, roles: [ROLE_ADMIN] }
        - { path: ^/admin/subscription, roles: [ROLE_ADMIN] }
        - { path: ^/admin/newsletter, roles: [ROLE_ADMIN] }
        - { path: ^/admin/shipping, roles: [ROLE_ADMIN] }
        - { path: ^/admin/sliders, roles: [ROLE_ADMIN] }
        - { path: ^/admin/dashboard, roles: [ROLE_ADMIN, ROLE_COMPANY] }
        - { path: ^/admin/analitycs, roles: [ROLE_ADMIN] }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_COMPANY, ROLE_USER] }
        - { path: ^/company/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/company, roles: [ROLE_COMPANY] }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/oauth/v2/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
